### ISSUE TITLE
How do I visualize the results coming from the pretrained model?

### ISSUE THREAD

**Issue by CtfChan** [PRBonn/bonnet#28]
I tried to run the following command.

train_py$ ./cnn_freeze.py -i ~/Downloads/leftImg8bit/train/aachen/aachen_000001_000019_leftImg8bit.png -l ~/Desktop/log -p ~/Downloads/city_1024/

It saved a bunch of files in my ~/Desktop/log. Now how do I visualize the output masks?

**Comment by tano297** [comment]
Hello, 
That is not the way to get the masks. Freezing the model puts the binaries in different formats for different backends. For usage information please refer to the python [readme](https://github.com/PRBonn/bonnet/blob/master/train_py/README.md)
