### ISSUE TITLE
ImportError: No module named arch.abstract_net

### ISSUE THREAD

**Issue by chowkamlee81** [PRBonn/bonnet#35]
I have executed ""python cnn_freeze.py -p /home/kumar/Experiments/city_512/"" but i landed with the error below

File "/home/kumar/Experiments/bonnet-master/train_py/arch/bonnet.py", line 31, in <module>
    from arch.abstract_net import AbstractNetwork
ImportError: No module named arch.abstract_net
Kindly help to solve the problem.

**Comment by Denlar2** [comment]
Think you need to use python3.

**Comment by chowkamlee81** [comment]
Got the one. Working fine.. Thanks ..
