### ISSUE TITLE
Using /gpu:1

### ISSUE THREAD

**Issue by thanhngotud** [PRBonn/bonnet#41]
Hi, 
I'm currently building bonnet application in PX2, but I'm not using ROS. At the moment, I can install the bonnet. But when I run bonnet, there is the problem of GPU device. 
In PX2, we have 2 gpu: iGPU and dGPU. The iGPU is the one only support fp16 and its locate in /gpu:1. 
I just want to ask is there any way to make Bonnet using /gpu:1, because at the moment it only accpet for gpu:0.

Best regards
Thanh

**Comment by thanhngotud** [comment]
I’m using tensorRT

**Comment by daniel89710** [comment]
"export cuda_visible_devices=1" enables us to use iGPU on PX2.

**Comment by thanhngotud** [comment]
Thanks for your help
