### ISSUE TITLE
ros catkin build Error in netTRT.cpp

### ISSUE THREAD

**Issue by LukiMuc** [PRBonn/bonnet#43]
Hallo,

I tried to build the package in ROS Kinetic on Jetson TX2 (Jetpack 3.3) and received following error:
![image](https://user-images.githubusercontent.com/46493213/50840989-0438cf00-1364-11e9-8fb2-8d8efbbec5f6.png)

Do anyone know why I receive this message?

Thanks

**Comment by tano297** [comment]
I'm not able to test it right now, but I had trouble with that API call in 3.3 and I created a branch "jetpack4.1-jetson-xavier" a couple of months ago. Can you test this branch to see if it is solved? Otherwise I will have to have a deeper look into it.

**Comment by LukiMuc** [comment]
With the new branch for Jetpack4.1 it builded with catkin.

Thank you! :+1:
